# Generated by Django 3.2.12 on 2022-03-08 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Name of Movie')),
                ('rank', models.IntegerField(verbose_name='Rank of Movie')),
                ('link', models.TextField(verbose_name='Link of IMDB page')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Link of IMDB page')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Link of IMDB page')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
