# Generated by Django 3.2.12 on 2022-03-08 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='first_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Movie First Seen At'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Movie Last Seen At'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='IMDB Rating'),
        ),
    ]
